### ISSUE TITLE
【仕様】ログインAPI【仮置き】

### ISSUE THREAD

**Issue by himaratsu** [handshakejp/dashboard-api#47]
## ログイン

* POST
* /session
* Parameter
 * username
 * password
* レスポンス
 * user_id
 * access_token
* エラー
 * error_message = 'cannot login'

## ログアウト

* DELETE
* /session
* Parameter
 * user_id
* レスポンス
 * result = 'OK'

## 新規登録

* POST
* /users
* Prameter
 * username
 * password
 * email
* レスポンス
 * user_id
 * access_token
* エラー
 * error_message = 'unrecognized error'

**Comment by shoma2da** [comment]
[Wiki](https://github.com/handshakejp/dashboard-api/wiki/API%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88#%E3%83%AD%E3%82%B0%E3%82%A4%E3%83%B3%E6%83%85%E5%A0%B1%E3%82%92%E5%8F%96%E5%BE%97%E3%81%99%E3%82%8B-post-session)に書いたので閉じちゃいます
